import { faPinterest, faReddit, faDailymotion, faDeviantart, faFacebook, faFlickr, faSnapchat,
    faSoundcloud, faSpotify, faApple, faTelegram, faGooglePlus, faTumblr, faTwitter, faInstagram,
    faVimeo, faLinkedin, faWhatsapp, faYoutube, faTiktok, faBehance} from '@fortawesome/free-brands-svg-icons';
import { faGlobe } from '@fortawesome/free-solid-svg-icons';

    const socialMedia = [{
        name: 'Pinterest',
        icon: faPinterest,
        color: '#E60023',
        contrast: '#FFFFFF',
        favorite: false
    }, {
        name: 'Reddit',
        icon: faReddit,
        color: '#FF4500',
        contrast: '#FFFFFF',
        favorite: false
    }, {
        name: 'Dailymotion',
        icon: faDailymotion,
        color: '#00A6D6',
        contrast: '#FFFFFF',
        favorite: false
    }, {
        name: 'Deviantart',
        icon: faDeviantart,
        color: '#05CC47',
        contrast: '#FFFFFF',
        favorite: false
    }, {
        name: 'Facebook',
        icon: faFacebook,
        color: '#3B5998',
        contrast: '#FFFFFF',
        favorite: false
    }, {
        name: 'Flickr',
        icon: faFlickr,
        color: '#0063DC',
        contrast: '#FFFFFF',
        favorite: false
    }, {
        name: 'Snapchat',
        icon: faSnapchat,
        color: '#FFFC00',
        contrast: '#000000',
        favorite: false
    }, {
        name: 'Soundcloud',
        icon: faSoundcloud,
        color: '#FF3300',
        contrast: '#FFFFFF',
        favorite: false
    }, {
        name: 'Spotify',
        icon: faSpotify,
        color: '#1DB954',
        contrast: '#FFFFFF',
        favorite: false
    }, {
        name: 'Apple',
        icon: faApple,
        color: '#000000',
        contrast: '#FFFFFF',
        favorite: false
    }, {
        name: 'Telegram',
        icon: faTelegram,
        color: '#0088CC',
        contrast: '#FFFFFF',
        favorite: false
    }, {
        name: 'Google Plus',
        icon: faGooglePlus,
        color: '#DD4B39',
        contrast: '#FFFFFF',
        favorite: false
    }, {
        name: 'Tumblr',
        icon: faTumblr,
        color: '#35465C',
        contrast: '#FFFFFF',
        favorite: false
    }, {
        name: 'Twitter',
        icon: faTwitter,
        color: '#1DA1F2',
        contrast: '#FFFFFF',
        favorite: false
    }, {
        name: 'Instagram',
        icon: faInstagram,
        color: '#E1306C',
        contrast: '#FFFFFF',
        favorite: false
    }, {
        name: 'Vimeo',
        icon: faVimeo,
        color: '#1AB7EA',
        contrast: '#FFFFFF',
        favorite: false
    }, {
        name: 'Linkedin',
        icon: faLinkedin,
        color: '#0077B5',
        contrast: '#FFFFFF',
        favorite: false
    }, {
        name: 'Whatsapp',
        icon: faWhatsapp,
        color: '#25D366',
        contrast: '#FFFFFF',
        favorite: false
    }, {
        name: 'Youtube',
        icon: faYoutube,
        color: '#FF0000',
        contrast: '#FFFFFF',
        favorite: false
    }, {
        name: 'Tiktok',
        icon: faTiktok,
        color: '#000000',
        contrast: '#FFFFFF',
        favorite: false
    }, {
        name: 'Behance',
        icon: faBehance,
        color: '#1769FF',
        contrast: '#FFFFFF',
        favorite: false
    }, {
        name: 'Web',
        icon: faGlobe,
        color: '#000000',
        contrast: '#FFFFFF',
        favorite: false
    }];
    
    export default socialMedia;